#!/usr/bin/env python
# Fetch timeseries by events
#
# Author: Mijian Xu
#
# History: 2016-06-07, Init code, Mijian Xu
#
import sys
import getopt
from util import Events, get_time
from datetime import datetime

def Usage():

def opt():
    lalo_label = ''
    dep_label = ''
    date_label = ''
    mag_label = ''
    sort_label = ''
    cata_label = 'GCMT'
    iscomment = True
    try:
        opts, args = getopt.getopt(sys.argv[1:], "R:D:b:e:c:H:M:O:")
    except:
        print("Invalid arguments")
        Usage()
        sys.exit(1)
    if sys.argv[1:] == []:
        print("No argument is found")
        Usage()
        sys.exit(1)
    if not ("-b" in [op for op, value in opts] and "-e" in [op for op, value in opts]):
        print("\"-b\" and \"-e\" must be specified.")
        sys.exit(1)

    for op, value in opts:
        if op == "-R":
            lalo_label = value
        elif op == "-D":
            lalo_label = value
        elif op == "-H":
            dep_label = value
        elif op == "-b":
            begintime = value
        elif op == "-e":
            endtime = value
        elif op == "-c":
            cata_label = value
        elif op == "-M":
            mag_label = value
        elif op == "-P"

